[project]
name = "tagging-engine"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fashion-clip>=0.2.2",
    "fastapi[standard]>=0.115.12",
    "ftfy>=6.3.1",
    "httpx>=0.28.1",
    "numpy>=2.2.6",
    "open-clip-torch>=2.32.0",
    "opencv-python-headless>=4.11.0.86",
    "pillow>=11.2.1",
    "pycocotools>=2.0.10",
    "python-dotenv>=1.1.0",
    "qdrant-client>=1.14.2",
    "sam2>=1.1.0",
    "scenedetect[opencv-headless]>=0.6.6",
    "supervision>=0.25.1",
    "torch>=2.6.0",
    "transformers[torch]>=4.51.3",
]

[tool.uv.sources]
torch = [
  { index = "pytorch-cu124", marker = "sys_platform == 'win32' or sys_platform == 'linux'" },
]

[[tool.uv.index]]
name = "pytorch-cu124"
url = "https://download.pytorch.org/whl/cu124"
explicit = true
